### ISSUE TITLE
wtsexporter -a error under wakbe/extracted folder

### ISSUE THREAD

**Issue by beckietech** [KnugiHK/Whatsapp-Chat-Exporter#1]
wtsexporter -a
Traceback (most recent call last):
  File "/usr/local/bin/wtsexporter", line 11, in <module>
    load_entry_point('whatsapp-chat-exporter==0.6', 'console_scripts', 'wtsexporter')()
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 473, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/whatsapp_chat_exporter-0.6-py3.5.egg/Whatsapp_Chat_Exporter/__main__.py", line 11
    parser = OptionParser(version=f"Whatsapp Chat Exporter: {__version__}")
                                                                         ^
SyntaxError: invalid syntax

Please let me know what am I missing?

**Comment by KnugiHK** [comment]
It is cause by Python. I notice that you are using Python 3.5 which is an old version of Python. However, this exporter requires at least Python 3.6 to work.

**Comment by beckietech** [comment]
Thank you! I'll try update python and retry! May I know the uninstall command of this project?

**Comment by KnugiHK** [comment]
No problem.
```shell
pip uninstall whatsapp-chat-exporter
```

**Comment by beckietech** [comment]
thanks again! I'll do it and update.

**Comment by KnugiHK** [comment]
I had put python_requires='>=3.7' in setup.py. May I know how did you install the exporter?

**Comment by beckietech** [comment]
I installed through python3 setup.py install.

**Comment by beckietech** [comment]
I tried install with python3.9, and the following:
python3.9 setup.py build
Traceback (most recent call last):
  File "/home/beckibox/whace/setup.py", line 1, in <module>
    import setuptools
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 23, in <module>
    from setuptools.dist import Distribution
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 34, in <module>
    from setuptools import windows_support
  File "/usr/local/lib/python3.9/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

Does python3.9 work?

**Comment by KnugiHK** [comment]
Yes, 3.9 should works, my dev environment is Python 3.9. May be you can try this: https://stackoverflow.com/a/48045929/9478891

**Comment by beckietech** [comment]
Thanks for the great work! it just worked. One thing to mention, when extracting from Android backup, there's empty media in result. May I know how to get these media files?

**Comment by KnugiHK** [comment]
Did you place the WhatsApp media folder in the working directory? The folder can be found in your Android phone external storage. And the file structure of the working directory be like:
| Working directory
|----- msgstore.db (main database)
|----- wa.db (contact list) (not necessary)
|----- WhatsApp (media folder extract from external storage)
        |----- Media
        |----- Backups (not necessary)
        |----- Databases (not necessary)

**Comment by beckietech** [comment]
I did create the folder structure accordingly and the run result also successful. however, I only see empty folders in those media folders, may I know how did it fetch from? Thanks.

**Comment by KnugiHK** [comment]
You meant your WhatsApp/Media is empty?

**Comment by beckietech** [comment]
yes, after success, the result folder created and WhatsApp and Media, subfolders moved under it . and the media subfolders contains empty.

**Comment by KnugiHK** [comment]
So, you mean media file are present before the program runs, and after the program ran, no media in the media subfolder? Or all media file are not present in anytime?

**Comment by beckietech** [comment]
all media are not presented ,thus I wonder where media can be fetched. I also saw:
Gathering contacts...(35)
Gathering messages...(11/11)
Gathering media...(7/7)
Gathering vCards...(0/0)
Creating HTML...(37/37)
Everything is done!

**Comment by KnugiHK** [comment]
You are working on Android right? WhatsApp store its media files in your phone external storage.
If you are using adb to fetch media the path will be: /sdcard/WhatsApp
If you connect you phone to a Linux machine: mtp:/<Your phone>/Internal shared storage/WhatsApp
If you connect you phone to a Windows machine: This PC\Nokia 9\Internal shared storage/WhatsApp

**Comment by KnugiHK** [comment]
You are working on Android right? WhatsApp store its media files in your phone external storage.
If you are using adb to fetch media the path will be: /sdcard/WhatsApp
If you connect you phone to a Linux machine: mtp:/<Your phone>/Internal shared storage/WhatsApp
If you connect you phone to a Windows machine: This PC\<Your phone>\Internal shared storage/WhatsApp

**Comment by beckietech** [comment]
I see, thanks!
