### ISSUE TITLE
NameError: name 'exit' is not defined

### ISSUE THREAD

**Issue by iconsofourtime** [KnugiHK/WhatsApp-Chat-Exporter#107]
# Must have
- WhatsApp version: 2.24.13.79
- OS: iOS - 17.5.1
- Platform: Windows
- Branch and version: WhatsApp Chat Exporter: 0.10.0 - exe file downloaded today
- 
If it is an error yield by Python, please also provide the trackback
```
PS C:\wabckp> .\wtsexporter_x64 -i -b "C:\Users\User1\Apple\MobileSync\Backup\00008110-001E490C0AEA901E"
Contact database not found.
Traceback (most recent call last):
  File "C:\Users\User1\AppData\Local\Temp\ONEFIL~1\__main__.py", line 519, in <module>
  File "C:\Users\User1\AppData\Local\Temp\ONEFIL~1\__main__.py", line 406, in main
  File "C:\Users\User1\AppData\Local\Temp\ONEFIL~1\Whatsapp_Chat_Exporter\ios_media_handler.py", line 99, in extract_media
NameError: name 'exit' is not defined
```

Powershell on Windows 10 Pro , iphone backup made with Apple Devices and later also with iTunes. Both on Windows. Does not work on both.

**Comment by KnugiHK** [comment]
Could you try to install the tool using pip?

**Comment by benoon** [comment]
Yes
```

PS C:\wabckp> python --version
Python 3.12.4

PS C:\wabckp> wtsexporter -i -b "C:\Users\User1\Apple\MobileSync\Backup\00008110-001E490C0AEA901E"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\wtsexporter.exe\__main__.py", line 4, in <module>
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 11, in <module>
    from Whatsapp_Chat_Exporter import ios_handler, ios_media_handler
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\Whatsapp_Chat_Exporter\ios_media_handler.py", line 12, in <module>
    from iphone_backup_decrypt import FailedToDecryptError
ImportError: cannot import name 'FailedToDecryptError' from 'iphone_backup_decrypt' (C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\iphone_backup_decrypt\__init__.py)

```

**Comment by iconsofourtime** [comment]
Sure.

```
PS C:\wabckp> python --version
Python 3.12.4

PS C:\wabckp> wtsexporter -i -b "C:\Users\User1\Apple\MobileSync\Backup\00008110-001E490C0AEA901E"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\wtsexporter.exe\__main__.py", line 4, in <module>
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 11, in <module>
    from Whatsapp_Chat_Exporter import ios_handler, ios_media_handler
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\Whatsapp_Chat_Exporter\ios_media_handler.py", line 12, in <module>
    from iphone_backup_decrypt import FailedToDecryptError
ImportError: cannot import name 'FailedToDecryptError' from 'iphone_backup_decrypt' (C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\iphone_backup_decrypt\__init__.py)

```

**Comment by KnugiHK** [comment]
> Sure.
> 
> ```
> PS C:\wabckp> python --version
> Python 3.12.4
> 
> PS C:\wabckp> wtsexporter -i -b "C:\Users\User1\Apple\MobileSync\Backup\00008110-001E490C0AEA901E"
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\wtsexporter.exe\__main__.py", line 4, in <module>
>   File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 11, in <module>
>     from Whatsapp_Chat_Exporter import ios_handler, ios_media_handler
>   File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\Whatsapp_Chat_Exporter\ios_media_handler.py", line 12, in <module>
>     from iphone_backup_decrypt import FailedToDecryptError
> ImportError: cannot import name 'FailedToDecryptError' from 'iphone_backup_decrypt' (C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\iphone_backup_decrypt\__init__.py)
> ```

Make sure you are installing the iphone_backup_decrypt with the master branch. For details of your issue, see https://github.com/KnugiHK/WhatsApp-Chat-Exporter/issues/102.

**Comment by iconsofourtime** [comment]
> If you are working on unencrypted iOS/iPadOS backup, skip this

I did not istall it because my iPhone backup is not encrypted.

Do I need to install it anyway?

**Comment by iconsofourtime** [comment]
I installed iphone_backup_decrypt using:
`pip install git+https://github.com/KnugiHK/iphone_backup_decrypt`
command and this is what's happening now:
`PS C:\wabckp> wtsexporter -i -b "C:\Users\User1\Apple\MobileSync\Backup\00008110-001E490C0AEA901E"
Contact database not found.
PS C:\wabckp>`
No errors, just that one line information about contact database and still no chat history export..

What should I do next?

**Comment by KnugiHK** [comment]
> > If you are working on unencrypted iOS/iPadOS backup, skip this
> 
> I did not istall it because my iPhone backup is not encrypted.
> 
> Do I need to install it anyway?

Oh... Then it seems there could be issue in the code. I will take a look later.

**Comment by KnugiHK** [comment]
> I installed iphone_backup_decrypt using: `pip install git+https://github.com/KnugiHK/iphone_backup_decrypt` command and this is what's happening now: `PS C:\wabckp> wtsexporter -i -b "C:\Users\User1\Apple\MobileSync\Backup\00008110-001E490C0AEA901E" Contact database not found. PS C:\wabckp>` No errors, just that one line information about contact database and still no chat history export..
> 
> What should I do next?

If you are sure you have WhatsApp (not WhatsApp Business) installed and exported it in the backup, then, probably they changed the database name, which requires changes to the code.

**Comment by iconsofourtime** [comment]
OK, can I use different branch or wait?

**Comment by KnugiHK** [comment]
Probably you will have to wait until I (or someone else who are willing to contribute) figure out the new things.

**Comment by KnugiHK** [comment]
> I installed iphone_backup_decrypt using: `pip install git+https://github.com/KnugiHK/iphone_backup_decrypt` command and this is what's happening now: `PS C:\wabckp> wtsexporter -i -b "C:\Users\User1\Apple\MobileSync\Backup\00008110-001E490C0AEA901E" Contact database not found. PS C:\wabckp>` No errors, just that one line information about contact database and still no chat history export..
> 
> What should I do next?

I could not reproduce the issue in iOS 17.6.1 with WhatsApp 2.24.17.78. It works fine with 0.10.0. Not sure what have been changed inside the WhatsApp app.

**Comment by nahcir** [comment]
I have exactly the same issue. Windows 11.

`C:\Users\richan\Downloads>wtsexporter_x64 -i -b "C:\Users\richan\AppData\Roaming\Apple Computer\MobileSync\Backup\00008120-000834CE1AEB401E"
WhatsApp database not found.
Traceback (most recent call last):
  File "C:\Users\richan\AppData\Local\Temp\ONEFIL~1\__main__.py", line 631, in <module>
  File "C:\Users\richan\AppData\Local\Temp\ONEFIL~1\__main__.py", line 490, in main
  File "C:\Users\richan\AppData\Local\Temp\ONEFIL~1\Whatsapp_Chat_Exporter\ios_media_handler.py", line 101, in extract_media
NameError: name 'exit' is not defined`

Inside the backup folder there are lots of other folders that are all two characters long, along with some .plist files. Is that correct?

**Comment by KnugiHK** [comment]
@iconsofourtime 
> Contact database not found.

The exporter will now continue running even when the contact database is not found.

@nahcir
Yes, disabling E2E encryption is now a necessary step for it to function correctly. This is already reported #125 and documented in the [Wiki](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/wiki/iOS-Usage#encrypted-iosipados-backup).

Regarding the 'exit not defined' issue, the root cause was traced back to the compiled binary's behavior. This should have been resolved in commit 0950306.

**Comment by KnugiHK** [comment]
Any issues regarding missing databases in the backup should be reported in #125 from now on. This issue will be focused on the NameError.

**Comment by KnugiHK** [comment]
Released in 0.12.0.
