### ISSUE TITLE
I'm trying to export an older backup from 2021 and I'm getting an error

### ISSUE THREAD

**Issue by 1cecream21** [KnugiHK/WhatsApp-Chat-Exporter#110]
# Must have
- WhatsApp version: something from 2021
- OS: Ios, probably 14
- Platform: Windows and Mac
- Branch and version: newest version on main

If it is an error yield by Python, please also provide the trackback
```
Traceback (most recent call last):
  File "C:\Users\icecream21\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\icecream21\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\icecream21\AppData\Local\Programs\Python\Python310\Scripts\wtsexporter.exe\__main__.py", line 7, in <module>
  File "C:\Users\icecream21\AppData\Local\Programs\Python\Python310\lib\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 406, in main
    ios_media_handler.extract_media(args.backup, identifiers, args.preserve_timestamp)
  File "C:\Users\icecream21\AppData\Local\Programs\Python\Python310\lib\site-packages\Whatsapp_Chat_Exporter\ios_media_handler.py", line 85, in extract_media
    extract_encrypted(base_dir, password, identifiers, preserve_timestamp)
  File "C:\Users\icecream21\AppData\Local\Programs\Python\Python310\lib\site-packages\Whatsapp_Chat_Exporter\ios_media_handler.py", line 23, in extract_encrypted
    backup.extract_file(
  File "C:\Users\icecream21\AppData\Local\Programs\Python\Python310\lib\site-packages\iphone_backup_decrypt\iphone_backup.py", line 272, in extract_file
    decrypted_data = self.extract_file_as_bytes(relative_path, domain)
  File "C:\Users\icecream21\AppData\Local\Programs\Python\Python310\lib\site-packages\iphone_backup_decrypt\iphone_backup.py", line 251, in extract_file_as_bytes
    return self.decrypt_inner_file(file_id=file_id, file_bplist=file_bplist)
  File "C:\Users\icecream21\AppData\Local\Programs\Python\Python310\lib\site-packages\iphone_backup_decrypt\iphone_backup.py", line 188, in decrypt_inner_file
    with open(filename_in_backup, 'rb') as encrypted_file_filehandle:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\WD Elements\\Backups\\Backup\\Backup 27.03.2021\\danie\\DANIELSMAC (2)\\Data\\C\\Users\\danie\\Apple\\MobileSync\\Backup\\bb33e5a01c2db55659cdaa63d6822d2dc238f5c9\\Snapshot\\7c\\7c7fba66680ef796b916b067077cc246adacf01d'
Decrypting WhatsApp database...
```

**Screenshots**
![image_2024-08-29_211855096](https://github.com/user-attachments/assets/6a9c627a-bbf7-44ad-a2f6-be9f4d9ddc36)

**Comment by jpfleischer** [comment]
what command are you executing that gives you that error

**Comment by KnugiHK** [comment]
Can you check if the following file exist?

```
D:\WD Elements\Backups\Backup\Backup 27.03.2021\danie\DANIELSMAC (2)\Data\C\Users\danie\Apple\\MobileSync\Backup\bb33e5a01c2db55659cdaa63d6822d2dc238f5c9\7c\7c7fba66680ef796b916b067077cc246adacf01d
```
