### ISSUE TITLE
[BUG] 2 Errors: self._cleanup() and unexpected keyword argument 'decrypt_chunk_size'

### ISSUE THREAD

**Issue by Box333** [KnugiHK/WhatsApp-Chat-Exporter#123]
# Must have
- WhatsApp Backup Extractor version: 10.5
- iOS - 17.x
- Platform: Windows 11
- Branch and version: main

Trackback:
```
Encryption detected on the backup!
Enter the password for the backup:
Trying to decrypt the iOS backup...WARN: Cleanup failed. You may want to delete the decrypted temporary file found at:
Exception ignored in: <function EncryptedBackup.__del__ at 0x00000248DC5D63E0>
Traceback (most recent call last):
  File "D:\Code\Python311\Lib\site-packages\iphone_backup_decrypt\iphone_backup.py", line 109, in __del__
    self._cleanup()
  File "D:\Code\Python311\Lib\site-packages\iphone_backup_decrypt\iphone_backup.py", line 118, in _cleanup
    print("    '{}'".format(self._temp_decrypted_manifest_db_path))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EncryptedBackup' object has no attribute '_temp_decrypted_manifest_db_path'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Code\Python311\Scripts\wtsexporter.exe\__main__.py", line 7, in <module>
  File "D:\Code\Python311\Lib\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 471, in main
    ios_media_handler.extract_media(args.backup, identifiers, args.decrypt_chunk_size)
  File "D:\Code\Python311\Lib\site-packages\Whatsapp_Chat_Exporter\ios_media_handler.py", line 86, in extract_media
    extract_encrypted(base_dir, password, identifiers, decrypt_chunk_size)
  File "D:\Code\Python311\Lib\site-packages\Whatsapp_Chat_Exporter\ios_media_handler.py", line 19, in extract_encrypted
    backup = EncryptedBackup(
             ^^^^^^^^^^^^^^^^
TypeError: EncryptedBackup.__init__() got an unexpected keyword argument 'decrypt_chunk_size'
```
Hi Knugi. 

Above ist the traceback of 2 Errors.

I installed a fresh python 3.11.09 and then Whatsapp_Chat_Exporter exatcly as described in the Wiki.

**Comment by KnugiHK** [comment]
Oops... Forgot to update [KnugiHK/iphone_backup_decrypt](https://github.com/KnugiHK/iphone_backup_decrypt). Please reinstall it from the main branch. The repo is undergoing significant rebasing, so let me know if you encounter any issues.

**Comment by Box333** [comment]
i found another small error in line 507 in __main__.py.

when using the --per-chat switch the code will not write json files, if the contact name has reserved characters such as "<>:".

**Comment by Box333** [comment]
its very simple to understand. If your conact name is "One>Way" for example, you have to strip or replace the ">" , because windows cant create filenames with ">" and your pre-chat function will fail.

**Comment by KnugiHK** [comment]
I added the `>` to one of the contact name and -j --per-chat works fine with the `>` being striped by the `sanitize_filename` function properly. 

If there are any error messages or stack trace, please share.

**Comment by Plancktron** [comment]
Hello, I have the same error when trying to run whatsapp-chat-exporter. Box333 mentioned that they were able to fix the error using version 0.10.0, however I could only find 0.9.0. 

Error snippet:
```
Encryption detected on the backup!
Enter the password for the backup:
Trying to decrypt the iOS backup...WARN: Cleanup failed. You may want to delete the decrypted temporary file found at:
Exception ignored in: <function EncryptedBackup.__del__ at 0x000001A84AA65080>
Traceback (most recent call last):
  File "C:\Users\maple\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\iphone_backup_decrypt\iphone_backup.py", line 58, in __del__
    self._cleanup()
  File "C:\Users\maple\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\iphone_backup_decrypt\iphone_backup.py", line 67, in _cleanup
    print(f"    '{self._temp_decrypted_manifest_db_path}'")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EncryptedBackup' object has no attribute '_temp_decrypted_manifest_db_path'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\maple\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\wtsexporter.exe\__main__.py", line 7, in <module>
  File "C:\Users\maple\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 711, in main
    ios_media_handler.extract_media(args.backup, identifiers, args.decrypt_chunk_size)
  File "C:\Users\maple\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Whatsapp_Chat_Exporter\ios_media_handler.py", line 231, in extract_media
    extractor.extract()
  File "C:\Users\maple\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Whatsapp_Chat_Exporter\ios_media_handler.py", line 34, in extract
    self._extract_encrypted_backup()
  File "C:\Users\maple\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Whatsapp_Chat_Exporter\ios_media_handler.py", line 67, in _extract_encrypted_backup
    self._decrypt_backup(password)
  File "C:\Users\maple\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Whatsapp_Chat_Exporter\ios_media_handler.py", line 78, in _decrypt_backup
    self.backup = EncryptedBackup(
                  ^^^^^^^^^^^^^^^^
TypeError: EncryptedBackup.__init__() got an unexpected keyword argument 'cleanup'
```

**Comment by KnugiHK** [comment]
Looks like Pypi does not like it. So, the `["ios_backup"]` optional dependency has been removed. User will have to install the dependency through the old way.
