### ISSUE TITLE
Error exporting iPhone backup from windows with Python 3.10.4

### ISSUE THREAD

**Issue by kintaro1981** [KnugiHK/Whatsapp-Chat-Exporter#13]
I'm getting this error (Python 3.10.4):

c:\Users\myusername\Desktop\working_wts>wtsexporter -i -b "C:\Users\myusername\AppData\Roaming\Apple Computer\MobileSync\Backup\myid"
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\wtsexporter.exe\__main__.py", line 4, in <module>
  File "C:\Python310\lib\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 2, in <module>
    from Whatsapp_Chat_Exporter import extract, extract_iphone
  File "C:\Python310\lib\site-packages\Whatsapp_Chat_Exporter\extract.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by KnugiHK** [comment]
Oh, that dependency should not be included for now. I will remove it later. In the meantime, you can install the dependency with 
"pip install requests" as a workaround.

**Comment by kintaro1981** [comment]
thank you 👍 
I have another issue now, I'm going to open a new one. 😭

**Comment by KnugiHK** [comment]
Fixed in commit https://github.com/KnugiHK/Whatsapp-Chat-Exporter/commit/042f6f9024f6ae6d7c7962743404f4df5933a4ce. I will leave this issue open until next release

**Comment by KnugiHK** [comment]
Released: https://github.com/KnugiHK/Whatsapp-Chat-Exporter/releases/tag/0.8.5
