### ISSUE TITLE
no such table: messages

### ISSUE THREAD

**Issue by sephiroth-croft** [KnugiHK/Whatsapp-Chat-Exporter#21]
Gathering contacts...(39)
Traceback (most recent call last):
  File "c:\users\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\Scripts\wtsexporter.exe\__main__.py", line 7, in <module>
  File "c:\users\appdata\local\programs\python\python37-32\lib\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 167, in main
    messages(db, data)
  File "c:\users\appdata\local\programs\python\python37-32\lib\site-packages\Whatsapp_Chat_Exporter\extract.py", line 195, in messages
    c.execute("""SELECT count() FROM messages""")
sqlite3.OperationalError: no such table: messages

I got the above error while trying to view messages. Please help to fix it.

**Comment by KnugiHK** [comment]
Duplication of #9
