### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by YuvrajRaghuvanshiS** [KnugiHK/Whatsapp-Chat-Exporter#4]
I see some of your programming constraints make in interrupt prematurely. 

- [ ] Like an instance where it could not find `WhatsApp` directory and interrupts. What I suggest you do is in your __init__.py or __main__.py you first write some checks and if required make those directories.

```python
import os
if(not os.path.isdir('WhatsApp'):
   os.mkdir('WhatsApp')
```
```
Traceback (most recent call last):
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Yuvraj\AppData\Local\Programs\Python\Python39\Scripts\wtsexporter.exe\__main__.py", line 7, in <module>
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 122, in main
    vcard(db, data)
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\site-packages\Whatsapp_Chat_Exporter\extract.py", line 244, in vcard
    os.mkdir(base)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'WhatsApp/vCards'
```

- [ ] Avoid permission denied: You can wait for some time before deleting the folder so that it gets free from any process using it.
```python
import time
time.sleep(3)
```
```
Gathering vCards...(67/67)
Traceback (most recent call last):
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\shutil.py", line 806, in move
    os.rename(src, real_dst)
PermissionError: [WinError 5] Access is denied: 'WhatsApp' -> 'result/WhatsApp'
```

-[ ] Still better for any non crucial operation like deleting temp folders do that in 
```python
try:
   # to delete folder
except:
   pass
```

because your code cascades into being totally dead on an exception

```
Traceback (most recent call last):
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\shutil.py", line 806, in move
    os.rename(src, real_dst)
PermissionError: [WinError 5] Access is denied: 'WhatsApp' -> 'result/WhatsApp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Yuvraj\AppData\Local\Programs\Python\Python39\Scripts\wtsexporter.exe\__main__.py", line 7, in <module>
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 126, in main
    shutil.move(options.media, f"{options.output}/")
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\shutil.py", line 818, in move
    rmtree(src)
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\yuvraj\appdata\local\programs\python\python39\lib\shutil.py", line 620, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'WhatsApp'
```

**Comment by KnugiHK** [comment]
For the first suggestion, there is a fix in the dev branch already.
For the second and the last, I will investigate them further.
Thanks for your suggestions!

**Comment by KnugiHK** [comment]
For the second and the third suggestions, I will put `shutil.move` under a try except block. And if exception(s) raise, simply show a warning to the user. The empty directory (WhatsApp) needs to be deleted manually by users.

**Comment by KnugiHK** [comment]
> For the second and the third suggestions, I will put `shutil.move` under a try except block. And if exception(s) raise, simply show a warning to the user. The empty directory (WhatsApp) needs to be deleted manually by users.

Implemented in commit [9140c07](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/commit/9140c07feb28420601471d6269bcf630021e2f81). Feel free to check it out and give comments. If no further comments are raised, I will leave this issue open until it is being released.
