### ISSUE TITLE
No such table  messages

### ISSUE THREAD

**Issue by mian196** [KnugiHK/Whatsapp-Chat-Exporter#40]
i got this error while exporting chats.

Gathering contacts...(187)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\*****\Desktop\Whatsapp-Chat-Exporter-0.8.5\Whatsapp_Chat_Exporter\wtsexporter.exe\__main__.py", line 7, in <module>
  File "C:\Users\*****\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 174, in main
    messages(db, data)
  File "C:\Users\*******\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Whatsapp_Chat_Exporter\extract.py", line 194, in messages
    c.execute("""SELECT count() FROM messages""")
sqlite3.OperationalError: no such table: messages

**Comment by KnugiHK** [comment]
Duplication of #9.
