### ISSUE TITLE
Getting error while processing iphone backup

### ISSUE THREAD

**Issue by KnugiHK** [KnugiHK/Whatsapp-Chat-Exporter#42]
### Discussed in https://github.com/KnugiHK/Whatsapp-Chat-Exporter/discussions/41

<div type='discussions-op-text'>

<sup>Originally posted by **ajay-ghub** May 16, 2023</sup>
```
> wtsexporter -i -j -b 'path/to/backup'
Gathering contacts...(425)7761)
Gathering messages...(141440/141440)
Gathering media...(31906/31906)
Traceback (most recent call last):
  File "/usr/local/bin/wtsexporter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/Whatsapp_Chat_Exporter/__main__.py", line 244, in main
    create_html(
TypeError: create_html() takes from 2 to 5 positional arguments but 6 were given
```
</div>

**Comment by ajay-ghub** [comment]
Thank you for the quick response, the fix is working for me.

**Comment by KnugiHK** [comment]
Good to hear that. I forgot the exporter include a iOS version🤨, hence, didn't test it.
