### ISSUE TITLE
sqlite3.OperationalError: Could not decode to UTF-8 column 'data' with text 'there is some text here and shards of question marks'

### ISSUE THREAD

**Issue by Stratos-Crimson** [KnugiHK/Whatsapp-Chat-Exporter#44]
Hello,
I suspect that this is due to some of the database not being in UTF-8.
I got around this on another program that also exports Whatsapp messages by adding the following code:
`db.text_factory = lambda b: b.decode(errors = 'ignore')`
after this code which was already there,
`db = sqlite3.connect(file_path)`
But when I tried to do this in this program,
I couldn't find It in the extract python files.
I instead found,
this....
```
if os.path.isfile(contact_db):
    with sqlite3.connect(contact_db) as db:
        contacts(db, data)
if os.path.isfile(msg_db):
    with sqlite3.connect(msg_db) as db:
        messages(db, data)
        media(db, data, media_folder)
        vcard(db, data)
    create_html(data, output_folder)
```
Which is beyond my understanding.

**Comment by KnugiHK** [comment]
You can place the line as follow:
```python
if os.path.isfile(contact_db):
    with sqlite3.connect(contact_db) as db:
        db.text_factory = lambda b: b.decode(errors = 'ignore') # here
        contacts(db, data)
if os.path.isfile(msg_db):
    with sqlite3.connect(msg_db) as db:
        db.text_factory = lambda b: b.decode(errors = 'ignore') # and here
        messages(db, data)
        media(db, data, media_folder)
        vcard(db, data)
    create_html(data, output_folder)
```

Also, could you provide me a stack trace related to this error and the version of the exporter you are using?

**Comment by Stratos-Crimson** [comment]
Oh thanks, sorry for not providing It before.
```
Traceback (most recent call last):)
  File "/home/user/.local/bin/wtsexporter", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/Whatsapp_Chat_Exporter/__main__.py", line 240 in main
    messages(db, data)
  File "/home/user/.local/lib/python3.9/site-packages/Whatsapp_Chat_Exporter/extract.py", line 380 in messages
  content = c.fetchone()
sqlite3.OperationalError: Could not decode to UTF-8 column 'data' with text '{placeholder}'
```

**Comment by KnugiHK** [comment]
> Oh thanks, sorry for not providing It before.
> 
> ```
> Traceback (most recent call last):)
>   File "/home/user/.local/bin/wtsexporter", line 8, in <module>
>     sys.exit(main())
>   File "/home/user/.local/lib/python3.9/site-packages/Whatsapp_Chat_Exporter/__main__.py", line 240 in main
>     messages(db, data)
>   File "/home/user/.local/lib/python3.9/site-packages/Whatsapp_Chat_Exporter/extract.py", line 380 in messages
>   content = c.fetchone()
> sqlite3.OperationalError: Could not decode to UTF-8 column 'data' with text '{placeholder}'
> ```

No problem.

Do you know what's the language and what encoding the message is used?

**Comment by Stratos-Crimson** [comment]
I am using the latest one.
When I tried to use It before your update, It was giving me that message table error but now that you have updated It, that's gone.
This is literally the terminal output of the text:
Keep it up�����������������������������������

**Comment by Stratos-Crimson** [comment]
I have just run a grep command on all of the messages and after seeing the messages I think that this is most likely this emoji "💪" times 4.

**Comment by Stratos-Crimson** [comment]
> You can place the line as follow:
> 
> ```python
> if os.path.isfile(contact_db):
>     with sqlite3.connect(contact_db) as db:
>         db.text_factory = lambda b: b.decode(errors = 'ignore') # here
>         contacts(db, data)
> if os.path.isfile(msg_db):
>     with sqlite3.connect(msg_db) as db:
>         db.text_factory = lambda b: b.decode(errors = 'ignore') # and here
>         messages(db, data)
>         media(db, data, media_folder)
>         vcard(db, data)
>     create_html(data, output_folder)
> ```
> 
> Also, could you provide me a stack trace related to this error and the version of the exporter you are using?
Adding this line didn't help.
But I only added It to the extract command and since the error is specifying the data column, this could be because of that.
Any thoughts?

**Comment by KnugiHK** [comment]
I tried to reproduce it but failed, the message shown in the HTML correctly.
![image](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/assets/24708955/f8a5d9f5-9539-4f7a-9e71-9583851d7c20)

You can use a SQLite browser to extract that message out and convert it into HEX. Doing so may enable me to reproduce the problem.

**Comment by Stratos-Crimson** [comment]
Which SQlite browser do I use?

**Comment by Stratos-Crimson** [comment]
I have tried to search for It using sqlitebrowser in the message table and data column but I couldn't find It.
Can I find out which row It's erroring out on?

**Comment by Stratos-Crimson** [comment]
Wait, I think that I have found It!
I just searched for the question mark shard and found 3 messages.
There is one which just has BLOB written on It.
And when I opened It, It showed me the Keep It up message and a bunch of dots.
It is also saying that the type of data that's currently in the cell is Binary.

**Comment by KnugiHK** [comment]
> I have tried to search for It using sqlitebrowser in the message table and data column but I couldn't find It. Can I find out which row It's erroring out on?

Replace
```python
        i += 1 # around line 377 of extract.py?
        if i % 1000 == 0:
            print(f"Gathering messages...({i}/{total_row_number})", end="\r")
        content = c.fetchone()
```
with
```python
        i += 1
        print(content["_id"])
        content = c.fetchone()
```
When you run that, the next row the printed `_id` should be the row that causing the problem.

**Comment by Stratos-Crimson** [comment]
This is the HEX and ASCII:
0000  4b 65 65 70 20 69 74 20 75 70 f0 9f 92 90 f0 9f  Keep it up...... 
0010  92 90 f0 9f 92 90 f0 9f 8c b9 f0 9f 8c b9 f2 a3  ................ 
0020  b0 bd f0 b7 a0 bd f0 b7 a0 bd ed b2 9e           .............

**Comment by KnugiHK** [comment]
> This is the HEX and ASCII: 0000 4b 65 65 70 20 69 74 20 75 70 f0 9f 92 90 f0 9f Keep it up...... 0010 92 90 f0 9f 92 90 f0 9f 8c b9 f0 9f 8c b9 f2 a3 ................ 0020 b0 bd f0 b7 a0 bd f0 b7 a0 bd ed b2 9e .............

Also, can you figure out the actual message shown in WhatsApp? Btw, just a reminder, do not post it publicly if it is a sensitive message.

**Comment by Stratos-Crimson** [comment]
You see, I have lost the Whatsapp encryption key and was only able to get the key file and this was before I deleted all of the Whatsapp backups.
Do you see anything sensitive in that message? I don't know HEX.

**Comment by Stratos-Crimson** [comment]
Hey, I am worried now, what is that HEX?

**Comment by Stratos-Crimson** [comment]
Hey so I did this:

echo 4b656570206974207570f09f9290f09f9290f09f9290f09f8cb9f09f8cb9f2a3b0bdf0b7a0bdf0b7a0bdedb29e | xxd -r -p

And got this:

Keep it up💐💐💐🌹🌹򣰽𷠽𷠽<dc9e>

**Comment by Stratos-Crimson** [comment]
Is there a way to ignore this error and let It run?

**Comment by KnugiHK** [comment]
> Hey, I am worried now, what is that HEX? cold_sweat

I don't mean to scare you. I have yet to look into the hex before you post the result tbh.

> Is there a way to ignore this error and let It run?

The easiest way is use a try except block and skip it but it is not an ideal solution.

I am still trying to reproduce it because the exporter failed after inserting a row with your binary content, but I got a different error than yours.
```
Traceback (most recent call last):
  ...
  File "...\Whatsapp_Chat_Exporter\extract.py", line 371, in messages
    if "\r\n" in msg:
TypeError: a bytes-like object is required, not 'str'
```

Does my screenshot below have any difference from yours?
![image](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/assets/24708955/18dfb349-cc44-4a6e-b025-e3c387ef615b)

**Comment by Stratos-Crimson** [comment]
Yes there is!
The first row is missing a 9f at the end.
And the 2nd row is missing an a3 at the end.

**Comment by KnugiHK** [comment]
Oh. They are just being hidden😂. Here you are:
![image](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/assets/24708955/f656a767-caf0-4288-b26d-d72a1fda64b8)

**Comment by Stratos-Crimson** [comment]
Hah, there is no difference than.
Did you try changing It from binary mode to text?

**Comment by KnugiHK** [comment]
> Hah, there is no difference than. Did you try changing It from binary mode to text or RTL text?

They can't be displayed in text or RTL mode. Try this and post the output:
```sql
SELECT quote(text_data) from message WHERE _id=<the message id>;
```

**Comment by Stratos-Crimson** [comment]
How?

**Comment by KnugiHK** [comment]
If you are using Linux/WSL:
```
sqlite3 msgstore.db
> SELECT quote(text_data) from message WHERE _id=<the message id>;
```

**Comment by Stratos-Crimson** [comment]
'Keep it up💐💐💐🌹🌹򣰽𷠽𷠽���'
Thanks. I got this.

**Comment by KnugiHK** [comment]
> 'Keep it upbouquetbouquetbouquetroserose򣰽𷠽𷠽���' Thanks. I got this.

Hmmm, you are supposed to get a hex string. Something like this:
![image](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/assets/24708955/111f0209-0f4a-4570-aab5-d4ffce142fdd)

**Comment by Stratos-Crimson** [comment]
I didn't get a hex. What version of sqlite3 command line are you using?
I am on 3.34.1.

**Comment by Stratos-Crimson** [comment]
Why is there no Id in your command?

**Comment by KnugiHK** [comment]
> I didn't get a hex. What version of sqlite3 command line are you using? I am on 3.34.1.

3.40.1

> Why is there no id in your command?

Look closer and you will find that it is just redacted😂. It should be an integer anyway.

**Comment by Stratos-Crimson** [comment]
Oh. Why would you redact that?!
I have just tried It with version 3.42.0 and It's still not giving me the hex.

**Comment by KnugiHK** [comment]
> Oh. Why would you redact that?! I have just tried It with version 3.42.0 and It's still not giving me the hex.

I guess that's mean we have different data in that cell.

**Comment by KnugiHK** [comment]
> Why are getting a hex anyway, the cell should contain the message, not the hex, right?

Yeah, I am trying to understand what raw data you got and how I can put the raw data into the cell. Hex is just one of the possible solutions, but we proved that we have different data inside the cell already by using hex. quote() function does not necessarily output hex but also just a quoted text.

What about this:
`sqlite3 -line msgstore.db 'SELECT quote(text_data) from message WHERE _id=<id>;' | hexdump -C`

**Comment by Stratos-Crimson** [comment]
But quote(texxt_data) =  is also going to be here so the hex won't match. Would It?

**Comment by Stratos-Crimson** [comment]
It will also have the quotes in the hex right? Wouldn't that be modifying the hex?

**Comment by KnugiHK** [comment]
Implemented the workaround for the problem in 9ac8839.

**Comment by KnugiHK** [comment]
> It will also have the quotes in the hex right? Wouldn't that be modifying the hex?

It doesn't necessarily be hex.

**Comment by Stratos-Crimson** [comment]
Does the workaround skip It or does It try to extract It? 

> Implemented the workaround for the problem in [9ac8839](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/commit/9ac8839ecc61b52e00d1c2da3d6673ebb6851370).



> > It will also have the quotes in the hex right? Wouldn't that be modifying the hex?
> 
> It doesn't necessarily be hex.

Did you put in the hex in the cell or the text?

**Comment by KnugiHK** [comment]
> Does the workaround skip It or does It try to extract It?


The workaround skip the message.

> Did you put in the hex in the cell or the text?


I put the hex in the hex area of the cell.

**Comment by Stratos-Crimson** [comment]
This is the output:
00000000  71 75 6f 74 65 28 74 65  78 74 5f 64 61 74 61 29  |quote(text_data)|
00000010  20 3d 20 27 4b 65 65 70  20 69 74 20 75 70 f0 9f  | = 'Keep it up..|
00000020  92 90 f0 9f 92 90 f0 9f  92 90 f0 9f 8c b9 f0 9f  |................|
00000030  8c b9 f2 a3 b0 bd f0 b7  a0 bd f0 b7 a0 bd ed b2  |................|
00000040  9e 27 0a                                          |.'.|
00000043

**Comment by Stratos-Crimson** [comment]
This is the plain hex,
71756f746528746578745f6461746129203d20274b656570206974207570f09f9290f09f9290f09f9290f09f8cb9f09f8cb9f2a3b0bdf0b7a0bdf0b7a0bdedb29e270a

**Comment by KnugiHK** [comment]
If you don't mind you can send me your database. It will the the easiest way to do debugging.

**Comment by Stratos-Crimson** [comment]
No can do.

**Comment by KnugiHK** [comment]
You can say Hi to me in the [Matrix room](https://matrix.to/#/!KtGjfSytJvzxewsXVd:matrix.org) and send the database to me through Matrix or send me an email with the link to the database at hello [at] knugi.com. You can find my PGP key at https://keyserver1.pgp.com.

**Comment by Stratos-Crimson** [comment]
Isn't there a way to extract a specific row from the database?

**Comment by KnugiHK** [comment]
Can you send me an INSERT statement to that row?

**Comment by Stratos-Crimson** [comment]
Pardon my ignorance but how do I do that?

**Comment by KnugiHK** [comment]
Use a supported browser to do it. Select the whole row and copy it as SQL.
![image](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/assets/24708955/c74df7fd-f2c3-47e9-94d3-af17cd82afe6)

**Comment by KnugiHK** [comment]
The workaround is released in 0.9.5.

**Comment by KnugiHK** [comment]
Fix released in 0.13.0
