### ISSUE TITLE
Error while doing an export

### ISSUE THREAD

**Issue by bhuwanchopra** [KnugiHK/WhatsApp-Chat-Exporter#72]
```
$$ wtsexporter -i -b ~/Library/Application\ Support/MobileSync/Backup/<device-id>
Encryption detected on the backup!
Enter the password for the backup:
Decrypting WhatsApp database...
Traceback (most recent call last):
  File "/Users/bhuwanchopra/Library/Python/3.9/bin/wtsexporter", line 8, in <module>
    sys.exit(main())
  File "/Users/bhuwanchopra/Library/Python/3.9/lib/python/site-packages/Whatsapp_Chat_Exporter/__main__.py", line 271, in main
    extract_iphone_media.extract_media(args.backup)
  File "/Users/bhuwanchopra/Library/Python/3.9/lib/python/site-packages/Whatsapp_Chat_Exporter/extract_iphone_media.py", line 73, in extract_media
    extract_encrypted(base_dir, password)
  File "/Users/bhuwanchopra/Library/Python/3.9/lib/python/site-packages/Whatsapp_Chat_Exporter/extract_iphone_media.py", line 22, in extract_encrypted
    backup.extract_file(relative_path=RelativePath.WHATSAPP_MESSAGES,
  File "/Users/bhuwanchopra/Library/Python/3.9/lib/python/site-packages/iphone_backup_decrypt/iphone_backup.py", line 272, in extract_file
    decrypted_data = self.extract_file_as_bytes(relative_path, domain)
  File "/Users/bhuwanchopra/Library/Python/3.9/lib/python/site-packages/iphone_backup_decrypt/iphone_backup.py", line 249, in extract_file_as_bytes
    file_id, file_bplist = result
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by KnugiHK** [comment]
Check if the follow SQL query return anything from the `Manifest.db` of the iOS backup?
```sql
SELECT fileID, file
FROM Files
WHERE relativePath = 'ChatStorage.sqlite'
AND flags=1
AND domain='AppDomainGroup-group.net.whatsapp.WhatsApp.shared'
ORDER BY domain, relativePath
LIMIT 1;
```

**Comment by haplessharpooneers** [comment]
I got the same issue.
