### ISSUE TITLE
OSError: [Errno 22] Invalid argument for iOS 

### ISSUE THREAD

**Issue by ishaand** [KnugiHK/WhatsApp-Chat-Exporter#75]
ran the code on Windows 11 (PowerShell 7.3.9) for unencrypted backup of iPhone.

`Extracting WhatsApp files...(156566/156566)

Processing contacts...(2289)

Traceback (most recent call last):94)

  File "C:\Users\user\AppData\Local\Temp\ONEFIL~1\__main__.py", line 389, in <module>

  File "C:\Users\user\AppData\Local\Temp\ONEFIL~1\__main__.py", line 312, in main

  File "C:\Users\user\AppData\Local\Temp\ONEFIL~1\Whatsapp_Chat_Exporter\extract_iphone.py", line 104, in messages

  File "C:\Users\user\AppData\Local\Temp\ONEFIL~1\Whatsapp_Chat_Exporter\data_model.py", line 62, in __init__

OSError: [Errno 22] Invalid argument`

Please help and guide. How can I help debug?

**Comment by ishaand** [comment]
Some say that it could be caused by a full disk - lack of storage. I'll clear more space on the computer and try again.

**Comment by ishaand** [comment]
I ran it again. I believe it is unrelated to storage. 
Also, earlier, with less storage I used to get OSError: [Errno 28] No space left on device

**Comment by KnugiHK** [comment]
Hi. It may be related to the time passed into the `datetime.fromtimestamp` function. You can print out the `time` variable to see what's inside.
