### ISSUE TITLE
Error on decrypt empty password

### ISSUE THREAD

**Issue by EdMarcus** [KnugiHK/WhatsApp-Chat-Exporter#8]
```python
b=iOSbackup(udid="00008030-0012742811E3802E", backuproot="C:\\Users\\edlon.sa\\Apple\\MobileSync\\Backup")
Traceback (most recent call last): 
File "<stdin>", line 1, in <module>
File "C:\Users\edlon.sa\AppData\Roaming\Python\Python310\site-packages\iOSbackup\__init__.py", line 190, in __init__ 
self.unlockKeys()
File "C:\Users\edlon.sa\AppData\Roaming\Python\Python310\site-packages\iOSbackup\__init__.py", line 1162, in unlockKeys
k = iOSbackup.AESUnwrap(self.decryptionKey,classkey[b"WPKY"])
File "C:\Users\edlon.sa\AppData\Roaming\Python\Python310\site-packages\iOSbackup\__init__.py", line 1214, in AESUnwrap
B = AES.new(key, AES.MODE_ECB).decrypt(todec)
File "C:\Python\Python310\lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
File "C:\Python\Python310\lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
return modes[mode](factory, **kwargs)
File "C:\Python\Python310\lib\site-packages\Crypto\Cipher\_mode_ecb.py", line 216, in _create_ecb_cipher
cipher_state = factory._create_base_cipher(kwargs)
File "C:\Python\Python310\lib\site-packages\Crypto\Cipher\AES.py", line 92, in _create_base_cipher
if len(key) not in key_size:
TypeError: object of type 'NoneType' has no len()
```

**Comment by KnugiHK** [comment]
This software does not use iOSbackup. What do you wanna do before the error raised?
